version: "3.3"
volumes:
  mysql-data:
services:
  mariadb:
    image: 'mariadb:latest'
    container_name: mariadb
    restart: on-failure
    environment:
      - "MYSQL_USER=admin"
      - "MYSQL_PASSWORD=admin"
      - "MYSQL_DATABASE=dev-env"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql/
  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector/configuration.yaml"]
    volumes:
      - ./observabilité/otel-collector/:/etc/otel-collector/
    restart: on-failure
    ports:
      - "4317:4317"   # grpc listen port
      - "8889:8889"
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: on-failure
    ports:
      - "16686:16686"
      - "6831:6831"
      - "14250:14250"
      - "14268:14268"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./observabilité/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    restart: always