all_animal_foods = [
    "Herbe",
    "Foin",
    "Maïs",
    "Orge",
    "Blé",
    "Carottes",
    "Choux",
    "Pommes",
    "Graine",
    "Fromage",
    "Noix",
    "Pain",
    "Carotte",
    "Avoine",
    "Betteraves",
    "Graine",
    "Vers de terre",
    "Insectes",
    "Oiseaux",
    "Rats",
    "Poissons",
    "BigMac",
    "Bucket de poulets",
    "Pizza",
    "Steak & Frites",
]
