{
 "title": "Flask HTTP",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(flask_exporter_info,instance)"
    }
   },
   {
    "name": "endpoint",
    "query": {
     "query": "label_values(flask_http_request_duration_seconds_bucket{instance=\"$instance\"},endpoint)"
    }
   },
   {
    "name": "status",
    "query": {
     "query": "label_values(flask_http_request_duration_seconds_count{instance=\"$instance\"},status)"
    }
   },
   { "name": "interval", "query": "30s,1m,2m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "Python Environment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Start date",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"$instance\"}*1000",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} used memory"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} available memory"
    }
   ]
  },
  {
   "title": "Flask exporter version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "targets": [
    { "expr": "flask_exporter_info{}", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Python version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "targets": [
    { "expr": "python_info{}", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "File Descriptors Usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} fds used"
    },
    {
     "expr": "process_max_fds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} fds max"
    }
   ]
  },
  {
   "title": "Rate Collected objects per GC ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total{generation=~\"0|1|2\",instance=~\"$instance\"}",
     "legendFormat": "[{{instance}}]  generation {{generation}}"
    },
    {
     "expr": "sum(python_gc_objects_collected_total{generation=~\"0|1|2\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "[{{instance}}]  total"
    }
   ]
  },
  {
   "title": "Uncollected objects during GC (by generation & total)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "python_gc_objects_uncollectable_total{generation=~\"0|1|2\",instance=~\"$instance\"}",
     "legendFormat": "[{{instance}}]  generation {{generation}}"
    },
    {
     "expr": "sum(python_gc_objects_uncollectable_total{generation=~\"0|1|2\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "[{{instance}}]  total"
    }
   ]
  },
  {
   "title": "Rate Collected objects per GC ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(python_gc_objects_collected_total{generation=~\"0|1|2\",instance=~\"$instance\"}[$interval])",
     "legendFormat": "[{{instance}}]  generation {{generation}}"
    },
    {
     "expr": "sum(rate(python_gc_objects_collected_total{generation=~\"0|1|2\",instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "[{{instance}}]  total"
    }
   ]
  },
  { "title": "Flask API global stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Request per second per instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{instance=~\"$instance\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Requests per second per HTTP response code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{instance=~\"$instance\",status=~\"$status\"}[$interval])) by (instance,status)",
     "legendFormat": "{{instance}} {{method }}  - {{status}}"
    }
   ]
  },
  { "title": "$instance $endpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }, "repeat": "endpoint" },
  {
   "title": "Response time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (instance, endpoint, le, status) (rate(flask_http_request_duration_seconds_bucket{instance=~\"$instance\", endpoint=~\"$endpoint\",status=~\"$status\"}[$interval])))",
     "legendFormat": "[{{instance}}]  p50  {{endpoint}} - {{status}}"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (instance,endpoint, le, status) (rate(flask_http_request_duration_seconds_bucket{instance=~\"$instance\", endpoint=~\"$endpoint\",status=~\"$status\"}[$interval])))",
     "legendFormat": "[{{instance}}]  p90  {{endpoint}} - {{status}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (instance,endpoint, le, status) (rate(flask_http_request_duration_seconds_bucket{instance=~\"$instance\", endpoint=~\"$endpoint\",status=~\"$status\"}[$interval])))",
     "legendFormat": "[{{instance}}] p99  {{endpoint}} - {{status}}"
    }
   ]
  },
  {
   "title": "Request rate per status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{instance=~\"$instance\",endpoint=~\"$endpoint\",status=~\"$status\"}[$interval])",
     "legendFormat": "{{endpoint}} {{status}}"
    }
   ]
  }
 ]
}